language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - development

matrix:
  allow_failures:
    - haxe: "3.4.7"

install:
  - haxelib install hxnodejs
  - haxelib dev electron .

script:
  - haxe --macro 'ElectronAPI.generate()'
  - haxe haxedoc.hxml
  - haxe --cwd demo build.hxml
